### ISSUE TITLE
The info on README to start the server doesn't work

### ISSUE THREAD

**Issue by villander** [contactlab/milky-way#392]
I tried to run the email package, running `npm install` on the root project, I'm getting the proper node_modules inside each package. but these commands to run the project does not work.

Could someone please help me with it? 

https://github.com/contactlab/milky-way/blob/0fd4e3d7278ab63196fd6537daeed49e29edbf06/packages/emails/README.md

Also, there's no one script on package.json to email package - https://github.com/contactlab/milky-way/blob/stable/packages/emails/package.json

**Comment by giotramu** [comment]
Hi @villander,

Thanks for reporting the issue.
Now should be fixed.

If you don't want to clone the project again, follow the instructions below:
- Launch the `npm run clean` command in the project root.
- Remove the root's `node_module` with `rm -rf node_modules` (it works in the Linux/Mac ecosystem).
- Finally, exec the `npm install` in the project root.

I'm sorry for the inconvenience.

**Comment by villander** [comment]
Thank you so much @giotramu
